/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package htw.berlin.wi.prog2;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SandwichBotApp {

    public static void main(String[] args) {
        SpringApplication.run(SandwichBotApp.class, args);
    }
}
